# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b676165b6fc4eab93b81a8aa2e2570d8b4d728d1b0dad888cac157021a06cecccb1e61e36f34fa613824e0222aacc2841152977340274931c895ab75ca421ec9

test:
  secret_key_base: 7e44227a7f75104b01e6e52933dbcf77f93af6d0c5da38630b020371254f04756584ed252f7f1385f4993bf45050c90ea28b3d6e641d299b1716091fc0fdf61b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
